// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqyyqhhafougprcnueek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeXlxaGhhZm91Z3ByY251ZWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTUyOTAsImV4cCI6MjA1Njg3MTI5MH0.DFK5ONSz-Wmocwv4s3YVl__s5PbCrVI6uoEW3OFQKxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);